# Generated by Django 3.0.8 on 2020-07-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start', models.CharField(help_text='Start time format: YYYY-MM-DDThh:mi:se+05:30 ex:2020-07-18T22:25:11+05:30', max_length=45)),
                ('end', models.CharField(help_text='End time format: YYYY-MM-DDThh:mi:se+05:30 ex:2020-07-18T22:25:11+05:30', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CreatedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlLink', models.CharField(blank=True, max_length=400, null=True)),
                ('hangoutLink', models.CharField(blank=True, max_length=400, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.Event')),
            ],
        ),
    ]
