# Generated by Django 2.2.10 on 2020-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_auto_20200623_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.TextField(max_length=45),
        ),
    ]
