# Generated by Django 2.2.10 on 2020-07-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_auto_20200708_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.CharField(max_length=45),
        ),
    ]
