# Generated by Django 2.2.10 on 2020-07-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20200708_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hangoutLink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='htmlLink',
        ),
        migrations.CreateModel(
            name='CreatedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlLink', models.CharField(blank=True, max_length=400, null=True)),
                ('hangoutLink', models.CharField(blank=True, max_length=400, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.Event')),
            ],
        ),
    ]
